# Generated by Django 3.2.6 on 2021-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='not available', upload_to='myimage'),
        ),
    ]
